sudo: required
language: cpp
notifications:
  email: false
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      services: docker
    - compiler: clang
      services: docker
before_install:
  - echo $CC; echo $CXX
    docker run -t -d -P -e "CC=$CC" -e "CXX=$CXX" --name devenv -v "$PWD"
script:
  - docker exec -t devenv /bin/sh -c "./sanity.sh"
